sonar.projectKey=VaibhavKapil1819_NeuralNotes
sonar.projectName=NeuralNotes
sonar.projectVersion=1.0

# Path to source directories
sonar.sources=backend,frontend/src,ai_pipeline

# Exclusions
sonar.exclusions=**/node_modules/**,**/venv/**,**/tests/**,**/*.test.tsx,**/*.test.ts,frontend/.next/**

# Language specific settings
sonar.python.version=3.13
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.python.coverage.reportPaths=coverage.xml

# Encoding
sonar.sourceEncoding=UTF-8
